import { defineConfig } from "cz-git";

export default defineConfig({
  ignores: [(commit) => commit.toLowerCase().includes("init")],
  extends: ["@commitlint/config-conventional"],
  parserPreset: {
    parserOpts: {
      // 支持 emoji
      headerPattern: /^(\p{Emoji})? ?(\w*)(?:\((.*)\))?: (.*)$/u,
      headerCorrespondence: ["emoji", "type", "scope", "subject"],
    },
  },
  rules: {
    // @see: https://commitlint.js.org/#/reference-rules
    "body-leading-blank": [2, "always"],
    "footer-leading-blank": [1, "always"],
    "header-max-length": [2, "always", 108],
    "subject-empty": [2, "never"],
    "type-empty": [2, "never"],
  },
  prompt: {
    alias: { fd: "docs: fix typos" },
    messages: {
      type: "选择你要提交的类型 :",
      scope: "选择一个提交范围（可选）:",
      customScope: "请输入自定义的提交范围 :",
      subject: "填写简短精炼的变更描述 :\n",
      body: '填写更加详细的变更描述（可选）。使用 "|" 换行 :\n',
      breaking: '列举非兼容性重大的变更（可选）。使用 "|" 换行 :\n',
      footerPrefixesSelect: "选择关联 issue 前缀（可选）:",
      customFooterPrefix: "输入自定义 issue 前缀 :",
      footer: "列举关联 issue (可选) 例如: #31, #I3244 :\n",
      generatingByAI: "正在通过 AI 生成你的提交简短描述...",
      generatedSelectByAI: "选择一个 AI 生成的简短描述:",
      confirmCommit: "是否提交或修改 commit ?",
    },
    types: [
      { value: "build", name: "📦 build:    构建相关        (部署脚本、Docker)", emoji: "📦" },
      { value: "chore", name: "🔨 chore:    日常维护        (依赖更新、配置调整)", emoji: "🔨" },
      { value: "ci", name: "🎡 ci:       CI/CD           (自动化流程、GitHub Actions)", emoji: "🎡" },
      { value: "docs", name: "📝 docs:     文档更新        (API文档、注释、README)", emoji: "📝" },
      { value: "feat", name: "✨ feat:     新增功能        (新业务、新逻辑)", emoji: "✨" },
      { value: "fix", name: "🐛 fix:      修复问题        (逻辑异常、接口错误)", emoji: "🐛" },
      { value: "init", name: "🎉 init:     初始化", emoji: "🎉" },
      { value: "perf", name: "⚡ perf:     性能优化        (缓存优化、响应速度)", emoji: "⚡" },
      { value: "refactor", name: "♻️  refactor: 代码重构        (优化代码结构、提升可维护性)", emoji: "♻️" },
      { value: "remove", name: "🔥 remove:   移除代码        (废弃接口、过期模块)", emoji: "🔥" },
      { value: "revert", name: "⏪ revert:   回退提交        (撤销之前的更改)", emoji: "⏪" },
      { value: "security", name: "🔒 security: 安全修复        (漏洞修复、权限控制)", emoji: "🔒" },
      { value: "style", name: "💄 style:    代码格式化      (代码格式化、样式修改、排版调整)", emoji: "💄" },
      { value: "test", name: "✅ test:     测试相关        (单元测试、集成测试)", emoji: "✅" },
      { value: "upgrade", name: "⬆️  upgrade:  升级依赖        (依赖包库升级)", emoji: "⬆️" },
    ],
    useEmoji: true,
    emojiAlign: "left",
    useAI: false,
    aiNumber: 1,
    themeColorCode: "",
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: "bottom",
    customScopesAlias: "custom",
    emptyScopesAlias: "empty",
    upperCaseSubject: null,
    markBreakingChangeMode: false,
    allowBreakingChanges: ["feat", "fix"],
    breaklineNumber: 100,
    breaklineChar: "|",
    skipQuestions: [],
    issuePrefixes: [{ value: "closed", name: "closed:   关联 ISSUE 已完成处理" }],
    customIssuePrefixAlign: "top",
    emptyIssuePrefixAlias: "skip",
    customIssuePrefixAlias: "custom",
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    scopeOverrides: undefined,
    defaultBody: "",
    defaultIssues: "",
    defaultScope: "",
    defaultSubject: "",
  },
});
